### ISSUE TITLE
[filebot] Movies and TV folder is wrong

### ISSUE THREAD

**Issue by javi11** [Cloudbox/Community#133]
I think the correct paths are:
- mnt/unionfs/Media/TV
- mnt/unionfs/Media/Movies

https://github.com/Cloudbox/Community/blob/a7320c9dbd87efcc8eb7cc5b8db25717135a62b9/roles/filebot/tasks/main.yml#L47

**Comment by Migz93** [comment]
They don't appear to be wrong?

The host paths are correct "/mnt/unionfs/Media/xx"
and the paths within container are based around the filebot image itself specifying "/storage" as the location for your files
https://github.com/jlesage/docker-filebot#data-volumes

**Comment by javi11** [comment]
True, but what about the Movies path is set /Movies/Movies
