### ISSUE TITLE
DelugeVPN issues

### ISSUE THREAD

**Issue by legionsystems** [Cloudbox/Community#139]
Getting the following error which seems to prevent DelugeVPN running properly.

insmod: ERROR: could not load module /lib/modules/iptable_mangle.ko: No such file or directory

The VPN tunnel comes up - but I get bad Gateway (from NGINX when attempting to connect to delugevpn.<domain> everytime

**Comment by jacekmusial** [comment]
Try this and tell if it have worked for you
* https://github.com/binhex/arch-delugevpn/issues/71#issuecomment-420260306
* https://github.com/binhex/arch-delugevpn/issues/57#issuecomment-378876929

Also I have found this post https://forums.unraid.net/topic/44109-support-binhex-delugevpn/?do=findComment&comment=634165 
Can you check that you do not have any of these?
> iptable_mangle support will not stop torrents from starting, that only prevents you accessing the web ui from outside your lan. i would guess that your issue is probably related to either running out of disk space on your host, or misconfigured volume mappings, such that the downloads are getting stored inside the loopback mounted docker image (unraid users only) so check for these things.

**Comment by bitbucket90** [comment]
Confirm the ovpn connection you are using allows port forwarding if that is your setup. Read the entire log or pastbin it as deluge and spit out a lot of red herrings.

**Comment by desimaniac** [comment]
Closing this as havent heard back from OP and they can get support from Discord channel.
