### ISSUE TITLE
Error when updating. /usr/bin/timedatectl set-timezone Europe/Berlin : Failed to set time zone: Access denied

### ISSUE THREAD

**Issue by GautierT** [Cloudbox/Community#145]
Hi. 
trying to update cloudbox so : `cd ~/cloudbox && sudo ansible-playbook cloudbox.yml --tags mediabox,emby,sonarr,radarr,jackett,organizr,ombi
`

But at the mediabox step i have this error.
```
TASK [system : Time Zone | Set time zone] **************************************************************************************************************************************
Sunday 27 October 2019  22:46:53 +0000 (0:00:01.124)       0:01:28.246 ********
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/timedatectl set-timezone Europe/Berlin", "msg": "Failed to set time zone: Access denied", "rc": 1, "stderr": "Failed to set time zone: Access denied\n", "stderr_lines": ["Failed to set time zone: Access denied"], "stdout": "", "stdout_lines": []}
```

And when trying to start an image who need the volumes /etc/localtime i have this error : 
```
Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/localtime\\\" to rootfs \\\"/var/lib/docker/overlay2/4cc41c40759648b1bfd89a3eac4b72f829b8989f6afc8f47ef249888f0c124fb/merged\\\" at \\\"/var/lib/docker/overlay2/4cc41c40759648b1bfd89a3eac4b72f829b8989f6afc8f47ef249888f0c124fb/merged/etc/localtime\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

Any idea ? Thanks !

**Comment by maximuskowalski** [comment]
With `sonarr,radarr,jackett,organizr,ombi `you probably want all in one `cloudbox `rather than `mediabox ` install.

Have you set the timezone in `adv_settings.yml`?
maybe
```
system: 
  timezone: Europe/Berlin
```
Have you updated cloudbox recently? And note this is community not cloudbox core.

https://github.com/Cloudbox/Cloudbox/wiki/Updating-Cloudbox

**Comment by GautierT** [comment]
Thanks @maximuskowalski.
Sorry i should have post on cloudbox not community...
I don't want to use cloudbox tags because their multiple things that i don't need in it.

Yes, timezone is set in `adv_settings.yml`

Yes i tried to update recently, i 
`cd ~/cloudbox && git fetch && git reset --hard @{u}` 
then when i 
`sudo ansible-playbook cloudbox.yml --tags mediabox` 
but with this last command i have this error : 
```
TASK [system : Time Zone | Set time zone] **************************************************************************************************************************************
Monday 28 October 2019  09:29:53 +0000 (0:00:00.112)       0:01:47.155 ********
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/timedatectl set-timezone Europe/Paris", "msg": "Failed to set time zone: Access denied", "rc": 1, "stderr": "Failed to set time zone: Access denied\n", "stderr_lines": ["Failed to set time zone: Access denied"], "stdout": "", "stdout_lines": []}
```
I'm on the develop branch. Is this related ? Thanks for your help.

**Comment by desimaniac** [comment]
@GautierT Run this command on CLI and see what it says:

```
sudo /usr/bin/timedatectl set-timezone Europe/Paris
```

**Comment by GautierT** [comment]
```
seed@Ubuntu-1804-bionic-64-minimal:~$ sudo /usr/bin/timedatectl set-timezone Europe/Paris
seed@Ubuntu-1804-bionic-64-minimal:~$
```
No error, no feedback...

And it seems to work.
```
seed@Ubuntu-1804-bionic-64-minimal:~$ cat /etc/timezone
Europe/Paris
```

**Comment by desimaniac** [comment]
Switch to dev branch. Not mounting /etc/localtime anymore: were too many issues with some servers making them into folders.

**Comment by GautierT** [comment]
Okay. Thanks !

**Comment by desimaniac** [comment]
Changes have been pushed to master as well.
