### ISSUE TITLE
Can't connect to Deluge via thin client

### ISSUE THREAD

**Issue by samsepiol59** [Cloudbox/Community#147]
Title says it all - I can't connect to my Deluge via thin client (on Windows)... no matter what I write in, it doesn't connect! Is this a known issue?

**Comment by hotio** [comment]
Title or the message says very little at all...so lucky guess: you are running deluge v2?

**Comment by samsepiol59** [comment]
V2, installed with the tag, allow_remote is enabled and set to true in core.conf, I've added a second username:password:10 in /opt/deluge/auth, I've restarted the container, classic mode is disabled in thin client

**Comment by hotio** [comment]
IIRC thin client does not support v2, it's mentioned in the release notes, no?

**Comment by hotio** [comment]
https://deluge.readthedocs.io/en/latest/releases/2.0.html#upgrade-considerations

**Comment by Migz93** [comment]
As advised by Hotio, there is no Windows client that supports V2, this isn't an issue with Community. You either need to swap to V1 deluge, or follow these steps https://dev.deluge-torrent.org/ticket/3201#comment:9.
Closing as theres nothing to be done Community end.
