### ISSUE TITLE
filebrowser role - source repo unmaintained

### ISSUE THREAD

**Issue by addbee** [Cloudbox/Community#178]
This repository has been archived by the owner.  
https://github.com/filebrowser/filebrowser

Was closed a few days ago.

I've run Cloud Commander as a replacement - if there's interest it can be merged in

https://github.com/addbee/cloudbox_cloudcmd

Only change required to merge it the Community cloudflare-dns task expects "record" instead of "subdomain"

**Comment by desimaniac** [comment]
Sure. 

The cloudflare params in CB will eventually get in sync with CM as role updates are brought in. I didn’t want to directly link to the CB roles since changes could break stuff here.

**Comment by Migz93** [comment]
It actually looks like filebrowser has been taken over by someone else now and is going back into active development.

If you wish for cloud commander to be included into Community then please raise a PR with the necessary changes.
