### ISSUE TITLE
Add Redbot

### ISSUE THREAD

**Issue by Peechaya** [Cloudbox/Community#182]
It would be nice to add Redbot, a Discord Bot.

Official repo:   https://github.com/Cog-Creators/Red-DiscordBot
Docker image: https://github.com/PhasecoreX/docker-red-discordbot

**Comment by Migz93** [comment]
You could follow this wiki page to add the discord bot
https://github.com/Cloudbox/Cloudbox/wiki/Add-Your-Own-Docker-Container-Into-Cloudbox

Then with the understanding of how to get it running you can create a role in community to create that container. Once you have it up and running you're welcome to raise a PR for its inclusion into Community.
