### ISSUE TITLE
jellyfin-nightly

### ISSUE THREAD

**Issue by steelersfan7** [Cloudbox/Community#190]
Would it be possible to replace the jellyfin docker from Linux Server to the jellyfin:jellyfin docker  so that it can get nightly and other updates? 

thanks

**Comment by desimaniac** [comment]
You can do nightly with LSIO one as well. 

`linuxserver/jellyfin:nightly`

Jellyfin one doesn't have UID/GID env support.

**Comment by steelersfan7** [comment]
I see, they literally added this less than two days ago. thanks!
