### ISSUE TITLE
delugevpn - will not connect to radarr,sonarr etc

### ISSUE THREAD

**Issue by bezzpezz** [Cloudbox/Community#200]
I have installed this "Community" edition to gain back the functionality of having torrent traffic go through a VPN - I have this on another server that I want to decommission due to old drives etc..
FYI these are home servers not cloud based, I don't want to outlay a lot of money for other servers when I have all the hardware I need at home.
With the delugevpn docker container it installs fine a   nd it even connects to my torguard vpn no problem (as long as I put the correct cert and opvn files in the config directory). The thing is I cannot connect the deluge vpn docker to any indexer instances in Radarr, Sonarr etc it just times out.
Is there any way to get this working? I have been trolling the net trying to find a solution but have had no luck. I think the issue is the main cloudbox uses nginx as a reverse proxy and I can connect to my delugevpn no problem using my cloudflare forwarded DNS e.g. delugevpn.mydomain.com. however I cannot put this into a indexer instance because it wants a port (8112 right? - wrong!).
Furthermore, there seems to be a lack of deluge vpn options in the settings.yml - the real vanilla deluge vpn has many configurable options like dns, lan config, data folders, not just the vpn login.
Any help with this will be appreciated.

I have tried to install rutorrentvpn as an alternative but this installs and runs but does not load properly (web interface has errors).
Are there any plans to add rtorrentvpn into community as this delugvpn seems very flawed?

**Comment by saltydk** [comment]
You are not supposed to add delugevpn.mydomain.com in radarr. You're supposed to use delugevpn and port 8112 (assuming that both dockers are on the same server) If we are talking about connecting remotely you would use delugevpn.mydomain.com with port 443 and HTTPS. Before you go an classify something as "flawed" at least do some kind of research.

**Comment by bezzpezz** [comment]
Thanks salty, your a lifesaver - using delugevpn and 8112 worked a treat!. My apologies, I was frustrated as there is no documentation and I spent hours researching and trolling. Such a simple solution. This should probably be made clearer in the Community and Cloudbox documentation so that radarr/sonarr/lidarr connections  are not assumed to be the server IP or radarr.domain etc. cheers

**Comment by maximuskowalski** [comment]
If you view the Deluge wiki as linked and instructed in the DelugeVPN wiki you will see the setup is actually shown in a screen shot.

https://github.com/Cloudbox/Community/wiki/Deluge#adding-to-sonarrradarr

**Comment by bezzpezz** [comment]
Thank you for your reply salty, let me first point out I actually meant radar/sonarr "Downloader" and not ""Indexer", Yes both dockers are on the same server,however, if what you state above is true I should be able to connect to delugevpn locally using e.g. 192.168.0.[server ip]:8112 or 127.0.0.1 or localhost but I get nothing on any port or variant

> If you view the Deluge wiki as linked and instructed in the DelugeVPN wiki you will see the setup is actually shown in a screen shot.
> https://github.com/Cloudbox/Community/wiki/Deluge#adding-to-sonarrradarr

Doh! Palm hits forehead firmly and stays there a little while.. Cheers!

**Comment by saltydk** [comment]
The delugevpn role publishes "127.0.0.1:8112:8112" which means that 8112 is only available on the host itself. If you want the ability to access this port on another machine you'd have to edit out the 127.0.0.1 and have "8112:8112". As I do not run delugevpn I have no idea how the vpn settings affect access outside of our cloudbox virtual network in docker as that seems to be the only thing listed as a LAN network in the role. As always you can see the configuration used on github: https://github.com/Cloudbox/Community/blob/master/roles/delugevpn/tasks/main.yml

**Comment by bezzpezz** [comment]
Ah ha, 

> The delugevpn role publishes "127.0.0.1:8112:8112" which means that 8112 is only available on the host itself. If you want the ability to access this port on another machine you'd have to edit out the 127.0.0.1 and have "8112:8112". As I do not run delugevpn I have no idea how the vpn settings affect access outside of our cloudbox virtual network in docker as that seems to be the only thing listed as a LAN network in the role. As always you can see the configuration used on github: https://github.com/Cloudbox/Community/blob/master/roles/delugevpn/tasks/main.yml

Ah ha! this a thing of beauty, things are becoming a lot clearer. Yes, Cloudbox installs as headless server instance of 16.04 (18.04 is not recommended) therefore no GUI for logging into / from the same machine. I was trying to login from another machine for config purposes, I guess a reverse proxy would possibly help for this? I am going to try and edit the roles for Nginx-proxy to forward the correct ports to things. Thanks salty!

**Comment by saltydk** [comment]
Not sure why you think 18.04 is not recommended since it is one of the two supported versions of Ubuntu. 18.10 on the other hand is not. https://github.com/Cloudbox/Cloudbox/wiki/Prerequisites%3A-Server

**Comment by Migz93** [comment]
Closing this issue as it seems bezzpezz's original issue was resolved by using the correct settings in sonarr/radarr.
