### ISSUE TITLE
First official release of code-server v3 removes the "--allow-http" flag and kills the coder container

### ISSUE THREAD

**Issue by codsane** [Cloudbox/Community#213]
First 'official' build of [code-server v3](https://github.com/cdr/code-server/releases/tag/3.0.2) was released today, and the [new image](https://hub.docker.com/layers/codercom/code-server/latest/images/sha256-ff785c1c004bee0574807e540e205d2d4293a96efb3c521d69f07c99461263d4?context=explore) just 6 hours ago. This means that [the "--allow-http" flag no longer exists](https://github.com/cdr/code-server/issues/1428#issuecomment-600729221).

If you have some kind of auto-update solution (ouroboros/watchtower/etc.) or the container/box was restarted, your code-server container might be perma-dead :(

I ended up removing the container, commented out the [line here](https://github.com/Cloudbox/Community/blob/master/roles/coder/tasks/main.yml#L50), and re-ran the coder tag.

**Comment by mrancier** [comment]
I just installed this container and ran into the issue with collabora not working.  I tried you solution, but it is still unreachable.  Any ideas on what else we can do to fix it ?

**Comment by codsane** [comment]
> I just installed this container and ran into the issue with collabora not working. I tried you solution, but it is still unreachable. Any ideas on what else we can do to fix it ?

This doesn't quite seem related to the original issue. I would suggest checking out the logs (`docker logs -f coder`) and creating a new issue, perhaps at [code-server](https://github.com/cdr/code-server) _if_ the issue ends up not being related to your Cloudbox configuration.
