### ISSUE TITLE
Stock NextCloud (OnlyOffice/Community Document Server) Failure

### ISSUE THREAD

**Issue by SalmonSays** [Cloudbox/Community#215]
Enabling the matching pair of Community Document Server and OnlyOffice apps from the NextCloud app marketplace with the Document Editing Service address pointing to the defaulted "https://nextcloud.domain.com/apps/documentserver_community/" results in the following not terribly specific error after opening a compatible docx/pptx/xlsx/etc file:

"ONLYOFFICE cannot be reached. Please contact admin"

Pulling open a browser console to log the error tells us: "GET https://nextcloud.domain.com/apps/documentserver_community/web-apps/apps/api/documents/api.js net::ERR_ABORTED 500"

As best I can tell, this is the result of some weird chain of communication starting with the domain address pointing to the document server internally then back to the outside world. I'm no expert on this subject, but I suspect it's likely broken by a stock Nginx-Proxy setting, Apache header or something similar. I suspect this because even routing to the public OnlyOffice demo server with valid certs results in a roughly similar error where compatible docx/pptx/xlsx/etc files similarly fail to load entirely and a plugin error is spat out.

**Comment by saltydk** [comment]
If you want support for Nextcloud you should go here https://github.com/linuxserver/docker-nextcloud or wherever linuxserver provides support. 

At any rate, this is unlikely to be something we can help you with since it is related to how the addons work within the docker itself.

**Comment by Migz93** [comment]
As advised by Salty, this is more related to app config with either nextcloud or nginx and support should be requested from them. Not related to community, closing.
