### ISSUE TITLE
Changed ports/image source/variables since docker image changed, rebased against develop.

### ISSUE THREAD

**Issue by theotocopulitos** [Cloudbox/Community#250]
Changed ports/image source/variables since docker image changed, rebased against develop.

_Originally posted by @RyanRadly in https://github.com/Cloudbox/Community/pull/226#issuecomment-640277956_

Randy, I find you need to change line 56 in main.yml:  demix -> deemix

Also, trying to run this, It loops over "successfully logged in / settings loaded!", and doesn't let me change any settings or search for anything

**Comment by Migz93** [comment]
@theotocopulitos thanks for raising those, I've mentioned them in the PR itself which you are also welcome to do for any future issues you see.

Closing this issue as tracking for it will be carried out within the PR itself.
