### ISSUE TITLE
Mylar3 created for wrong user (root) - Migrate to hotio image?

### ISSUE THREAD

**Issue by theotocopulitos** [Cloudbox/Community#256]
Mylar3 creates folders and files in host as "root" rather than as the corresponding cloudbox user.

The tasks file is basically the same as that for the Mylar role, so I am guessing the problem is not in the tasks.yml file but in the docker image used, ajslater/mylar3 .

I have not been able to troubleshoot this and find the root cause for this issue. However, it seems that switching to hotio image solves the problem... Is this the way to go?

**Comment by owine** [comment]
Yes this is why it is always preferable to use docker images that allow UID and GID to be defined (as hotio images do.) My suggestion would be to change to the hotio image (or another well-maintained and updated image that allows UID and GID to be defined.) I have a migrator tool in the bazarrx role (https://github.com/Cloudbox/Community/blob/develop/roles/bazarrx/subtasks/hotio_migration.yml) which could be easily adapted for any existing installations.

**Comment by theotocopulitos** [comment]
I see a problem with the automatic "migration"... unfortunately, some files are created by 'root', and I don't think script run by the regular user would be able to move those files :(

**Comment by Migz93** [comment]
The cloudbox command should always be run with sudo so there should be no issue moving files.

**Comment by ajslater** [comment]
The latest [ajslater/mylar3 ](https://hub.docker.com/repository/docker/ajslater/mylar3) image now supports PUID and PGID variables inspired by linuxserver. 

Feel free to send issues to github: https://github.com/ajslater/docker-mylar3/issues

Or hit me up on freenode #mylar @ajslater

**Comment by mrhotio** [comment]
@saltydk might be a good idea to switch to the prefered hotio image afterall since the other one isn't being updated anymore...

**Comment by saltydk** [comment]
Submit a PR if you want. I don't use mylar.

**Comment by mrhotio** [comment]
Me neither, don't even use cb...
