### ISSUE TITLE
Guacamole role - add tags for Duo authentication?

### ISSUE THREAD

**Issue by willjgit** [Cloudbox/Community#294]
Is there a way to have the guacamole role have tags for duo authentication? The package supports it but there is no way to role it out it seems with the community package.

**Comment by chazlarson** [comment]
How are these "tags" added, and what about the community role precludes that from happening?

**Comment by willjgit** [comment]
The docker image referenced in the guacamole role for the community repo does not have any documentation for it, but other docker images for guacamole such as here: https://hub.docker.com/r/oznu/guacamole/ reference the ability under "Enabling Extensions" to allow for auth-duo - Duo two-factor authentication or other two factor authentication methods. Guacamole's own docs also reference ability to implement two factor: https://guacamole.apache.org/doc/gug/duo-auth.html

The problem here is you can't edit the guacamole config directly because updating it using the ansible guacamole tag will override those custom configurations.

Would be nice to have extension tags available to allow for the implementation of two factor.

**Comment by saltydk** [comment]
I'm not seeing anything in the role that overrides any config files. What prevents you from just manually adding the extensions to the fight folder?

**Comment by willjgit** [comment]
You are right, it doesn't override any config files. Closing issue.
