### ISSUE TITLE
Add locast2plex to Community

### ISSUE THREAD

**Issue by pb1051** [Cloudbox/Community#299]
I'm just not educated in this stuff yet to make my own project and make it work. I think I'm only missing a few things to make it work on my machine, but it would be cool if someone could get it working before I pull all my hair out.

locast2plex is a cool add-on for Plex that accepts your Locast paid account feed as a Live TV feed.

Locast is a $5/month donation for your local channels streamed over the internet. It's an awesome little program.

[GitHub Project locast2plex](https://github.com/tgorgdotcom/locast2plex)
[One Guide for Docker](https://www.brad.farm/2020/08/25/tech-plex-locast-recording-local-tv-without-the-antenna/)
[Another verison of the guide](https://diyfuturism.com/index.php/2020/08/16/plex-locast-recording-local-tv-without-the-antenna/)

**Comment by chazlarson** [comment]
It would be valuable for you to share the work you've already done, or work with people on the discord to solve the "few things to make it work".  

Doing the pull request to add it is the simple part; if you've got it nearly working it would be better to leverage that work.

**Comment by owine** [comment]
Check out https://github.com/Cloudbox/Community/wiki/Contribute

**Comment by pb1051** [comment]
perfect. thank you.
_________________________________
Paul N. Bailey
Contact: (281)770-4796 <#SignatureSanitizer_SafeHtmlFilter_>

**Comment by kylefmohr** [comment]
Locast is now permanently shutdown (R.I.P) so I think this issue could be closed.
