### ISSUE TITLE
Request: xteve with VPN

### ISSUE THREAD

**Issue by jscottdouglas** [Cloudbox/Community#305]
Any chance someone could add xteve with VPN so that when using buffer it connects to the IPTV server via VPN?  I am new to docker otherwise I'd give it a go myself also terrible with iptables etc.  I see a docker already - https://github.com/brycelarge/xteve-vpn but i have no clue how to get this as a community role, or how to get it started

**Comment by ben-ba** [comment]
https://github.com/Cloudbox/Community/wiki/Contribute

https://github.com/Cloudbox/Community/wiki/IPTV
