### ISSUE TITLE
bitwarden desktop app+android app issue

### ISSUE THREAD

**Issue by wbui567** [Cloudbox/Community#306]
hello,
I installed bitwarden role.
I can connect via browser (firefox/chrome) and plugin desktop firefox (don't tested with chrome plugin).
I cannont connect via android app or desktop app
i receive an error "an unexpected error has occured"...
Did you already get this issue and, can you help me to fix it?
thanks.

**Comment by saltydk** [comment]
Go to our discord and maybe someone will be able to help you out. This repo is not for support on the various apps we include outside of them needing updates.

**Comment by wbui567** [comment]
what is the discord ?
Thanks

**Comment by chazlarson** [comment]
There's a link to the Discord server at the top of the Cloudbox Readme.
