### ISSUE TITLE
grafana

### ISSUE THREAD

**Issue by wbui567** [Cloudbox/Community#394]
Hello,
I did a fresh install of grafana, but credential admin/admin or credentials set up on ansible are not valid.
Do you know what is the default credentials?
Thanks.

**Comment by kungfoome** [comment]
This would be based on the user password you setup when you installed cloudbox:

https://github.com/Cloudbox/Community/blob/882fd1ce3aa4a519360c995077e65a26f9cc2d8f/roles/grafana/tasks/main.yml#L37
