### ISSUE TITLE
Update jellyfin

### ISSUE THREAD

**Issue by MaseSpace** [Cloudbox/Community#406]
my jellyfin container is out of date so far the app won't load the server anymore. im trying to update it using ` sudo ansible-playbook cloudbox.yml --tags jellyfin` but it errors. all in red shows this error. whats the tag for jellyfin? `failed: [localhost] (item=jellyfin) => {
    "assertion": "\"jellyfin\" in available_tags.stdout_lines", 
    "changed": false, 
    "evaluated_to": false, 
    "item": "jellyfin", 
    "msg": "You must supply valid tag(s) via '--tags TAG' (get a list of valid tags by running 'sudo ansible-playbook cloudbox.yml --list-tags')"
}`

**Comment by owine** [comment]
Since Jellyfin is part of the Community repo, you have to call the Community playbook.

`cd ~/community && sudo ansible-playbook community.yml --tags jellyfin`

**Comment by owine** [comment]
Try `/opt/community` then.

**Comment by MaseSpace** [comment]
That worked. thanks so much!
