### ISSUE TITLE
readarr failing: s6-overlay-suexec: fatal: can only run as pid 1

### ISSUE THREAD

**Issue by n0-0bface** [Cloudbox/Community#410]
Followed the deployment instructions for community containers and deployed readarr.

Container boot loops and logs kickout as:

`2022-12-19T18:32:55.113028857Z s6-overlay-suexec: fatal: can only run as pid 1
`

Looks like both linuxserver.io and hotio container versions of readarr are bombing due to `"init": true,` in `/etc/docker/daemon.json`.

Attempted manual installation, same issue. 

Wondering how vital using init as the entry point for existing cloudbox containers is.

**Comment by owine** [comment]
Update your main Cloudbox repo and run the Cloudbox `docker` tag which will remove that entry and allow the containers to work again.

**Comment by n0-0bface** [comment]
That worked. Thanks.
